/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ByEquipment: typeof import('./src/components/by-equipment.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpotsByEquipment: typeof import('./src/components/SpotsByEquipment.vue')['default']
  }
}
